# TE 2nd CAESAR CIPHER

print(f"a = {ord("a")}")
print(f"b = {ord("b")}")
print(f"c = {ord("c")}")
print(f"d = {ord("d")}")
print(f"e = {ord("e")}")
print(f"f = {ord("f")}")
print(f"g = {ord("g")}")
print(f"h = {ord("h")}")
print(f"i = {ord("i")}")
print(f"j = {ord("j")}")
print(f"k = {ord("k")}")
print(f"l = {ord("l")}")
print(f"m = {ord("m")}")
print(f"n = {ord("n")}")
print(f"o = {ord("o")}")
print(f"p = {ord("p")}")
print(f"q = {ord("q")}")
print(f"r = {ord("r")}")
print(f"s = {ord("s")}")
print(f"t = {ord("t")}")
print(f"u = {ord("u")}")
print(f"v = {ord("v")}")
print(f"a = {ord("w")}")
print(f"a = {ord("x")}")
print(f"a = {ord("y")}")